Semen-Gomzyak/pets-project-frontend

- src/components/App/App.jsx
- src/components/NewsList/NewsList.styled.js
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeCategoryList/NoticesCategoriesList.jsx
- src/components/Notices/NoticeCategoryList/NoticesCategoriesList.styled.js
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/Notices/NoticesOperations.js
- src/redux/Notices/NoticesSelector.js
- src/redux/Notices/NoticesSlice.js
- src/redux/store.js
- src/services/getNews.jsx
- src/services/getNoticesByCategory.jsx
the work logic of receiving a list of notices (part1), without styles
> Notice category list- logic

- src/components/App/App.jsx
- src/components/LoginForm/LoginForm.jsx
- src/components/Nav/Nav.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.styled.js
- src/components/Notices/NoticeCategoryList/NoticesCategoriesList.styled.js
- src/components/Notices/NoticesCategoriesNav/NoticesCategoryNav.jsx
- src/components/Notices/NoticesSearch/NoticesSearch.jsx
- src/index.js
- src/redux/Notices/NoticesOperations.js
- src/redux/Notices/NoticesSlice.js
Notice  addNotice +fetchOneNotice. + style Item+ toastNotificationFavorite
> Notice  addNotice +fetchOneNotice

- src/components/ButtonAddPet/AddPetBtn.jsx
- src/components/ButtonAddPet/AddPetBtn.styled.js
- src/components/ButtonNotice/BtnNotice.jsx
- src/components/ButtonNotice/BtnNotice.styled.js
- src/components/Nav/Nav.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.styled.js
- src/components/Notices/NoticeCategoryList/NoticesCategoriesList.jsx
- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/components/Notices/NoticeModal/NoticeModal.styled.js
- src/components/Notices/NoticesCategoriesNav/NoticesCategoryNav.jsx
- src/components/Notices/NoticesSearch/NoticesSearch.jsx
- src/components/SearchInput/SearchInput.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/pages/NoticesPage/NoticesPage.styled.js
- src/redux/Notices/NoticesOperations.js
Notice Route, Notiseitem, NoticeModal, BtnAddPet
> Notice Route, Notiseitem, NoticeModal, BtnAddPet

- src/components/Modal/Modal.styled.js
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/components/Registration/SecondRegisterForm.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/pages/Profile/Profile.jsx
update Modalstyle+ logic ModalNotice
> Notices modal bugfix

- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/Notices/NoticesOperations.js
- src/redux/Notices/NoticesSlice.js
> add deleteBtn

- src/components/Nav/Nav.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/Auth/operations.js
- src/services/getFaforites.jsx
> Route favorite

- src/components/Modal/Modal.styled.js
- src/components/Profile/Avatar/Avatar.jsx
- src/components/Profile/Avatar/Avatar.styled.js
- src/validations/UpdateUserFormValidation.js
> update form validation

- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/Notices/NoticesOperations.js
- src/redux/Notices/NoticesSelector.js
- src/redux/Notices/NoticesSlice.js
- src/services/getFaforites.jsx
> Route owner

- src/components/Notices/NoticesCategoriesNav/NoticesCategoryNav.jsx
- src/pages/NoticesPage/NoticesPage.jsx
> bugfix style BtnNavNotices

- src/components/Profile/ConfirmLogout/ConfirmLogout.jsx
- src/components/Profile/ConfirmLogout/ConfirmLogout.styled.js
- src/components/Profile/UserUpdateForm/UserUdateForm.jsx
- src/pages/Profile/Profile.jsx
> logout confirmation

- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/SharedLayout/SaredLayout.jsx
- src/components/WarningMessage/WarningMessage.jsx
- src/components/WarningMessage/WarningMessage.styled.js
button Delete  Notice+ logic+ style
> button Delet  Notice+ logic

- src/components/Nav/Nav.jsx
- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/pages/NoticesPage/NoticesPage.jsx
- src/redux/Auth/operations.js
- src/redux/Auth/slice.js
> Favorine Notice route finish

- src/components/Registration/FirstRegisterForm.jsx
- src/components/Registration/SecondRegisterForm.jsx
Додав до ЛокалСторедж тільки з першої сторінки Реєстрації
> add values to localstorage

- src/components/Modal/Modal.styled.js
- src/components/Profile/Avatar/Avatar.jsx
- src/components/Profile/PetList/PetList.jsx
- src/components/Profile/PetList/PetList.styled.js
- src/components/Profile/UserUpdateForm/UserUdateForm.jsx
- src/components/Profile/UserUpdateForm/UserUpdateForm.styled.js
- src/pages/Profile/Profile.jsx
- src/pages/Profile/Profile.styled.js
- src/services/api/user.js
Трохи порефакторив код, прибрав консоль-логи, підправив стилі
> refactored

- src/components/Registration/FirstRegisterForm.jsx
- src/components/Registration/SecondRegisterForm.jsx
Поки зробив лише на першій чторінці Реєстрації
> saving values when reloading

- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/pages/Profile/Profile.jsx
> add email and phone to notice

- src/components/Notices/NoticeCategoryList/NoticeCategoryItem.jsx
- src/components/Notices/NoticeModal/NoticeModal.jsx
Bugfix notis modal+ dataOneNotice
> Bugfix notis modal

- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/components/Profile/UserUpdateForm/UserUdateForm.jsx
- src/redux/Auth/operations.js
ніби поправив всі зауваження по профілю від ментора плюс додав лоадер на зміну аватару та кнопку редагування даних в формі. Розкоментував дві стрічки в NoticeModal, бо не працювало.
> Profile backup

- src/components/ButtonFavorite/BtnFavorite.styled.js
- src/components/Modal/Modal.jsx
- src/components/Modal/Modal.styled.js
- src/components/Notices/NoticeModal/NoticeModal.jsx
- src/components/Notices/NoticeModal/NoticeModal.styled.js
- src/components/SearchInput/SearchInput.jsx
- src/components/SearchInput/SearchInput.styled.js
- src/pages/NewsPage/NewsPage.jsx
- src/pages/NewsPage/NewsPage.styled.js
> Bugfix 3 6 7 9

- src/components/PetForm/PetForm.styled.jsx
Поправив стилі модалки для додавання тварини, відображалась для мобільних пристроїв з некоректними розмірами
> add pet modal
